---
domain: Samples
appId: banking-offers-app
groupId: io.provingly
appVersion: 1.0.0

provider:
  name: Provingly
  email: info@provingly.io

generateOpenApi: true
dependencies: []

localizedInfo:
  - label: Luego Validation, Eligibility and Pricing App
    description: A sample to show how to organize decisions in multiple folders
    tags: [ 'sample', 'eligibility', 'pricing' ]
    lang: en
    country: